### ISSUE TITLE
How to fold a partial string?

### ISSUE THREAD

**Issue by vphantom** [dbuenzli/uuseg#11]
Hello,

In order to make my string processing functions UTF-8 friendly, I iterate on incoming strings using: ``Uuseg_string.fold_utf_8 `Grapheme_cluster``.  This way, I keep grapheme clusters intact.

For versatility, I'd like to make my functions accept slices, i.e.:

```ocaml
(** [truncate max_len ?pos ?len str] returns a copy of [str] guaranteed not to exceed [max_len] bytes.
    Optional [pos] and [len] restrict the portion of [str] being copied. *)
var truncate : int -> ?pos:int -> ?len:int -> string -> string
```

The best I can come up with is to do my own accounting in my folding function but this isn't efficient if the string I want to parse is deep within a much longer chunk of data.  The way I see it, my usable options are: 1) just `String.iter` and tolerate the possibility of truncating grapheme clusters, 2) copy the string temporarily instead of reading it in-place, 3) figure out, with your guidance, a pull request so that `Uuseg_string` folders gain the ability to optionally be restricted to a slice of their input string.

I think I'll have to compromise with 2 today and maybe figure out 3 later, although I find your coding style a bit intimidating for my limited experience level with OCaml. 😬

What would you suggest?

**Comment by dbuenzli** [comment]
> In order to make my string processing functions UTF-8 friendly, I iterate on incoming strings using: `` Uuseg_string.fold_utf_8 `Grapheme_cluster ``. This way, I keep grapheme clusters intact.

UTF-8 doesn't care about grapheme clusters. So I'm not sure what keeping grapheme clusters intact has to do with being "UTF-8 friendly". You'd rather simply keep scalar value intact so that truncation doesn't result in invalid UTF-8.

But then I find your specification of `truncate` a bit curious. I'm not sure I see a use for defining a length in terms of bytes and then truncate according to grapheme clusters. When dealing with text you want to truncate e.g. for display, so indicating `max_len` in bytes seems unhelpful.

In any case I'd suggest 2) or doing it yourself with the streaming segmenters for now (just look at the code). As indicated [there](https://discuss.ocaml.org/t/ann-unicode-15-0-0-update-for-uucd-uucp-uunf-and-uuseg/10485) this will soon be rewritten to use the stdlib decoder. 

> I find your coding style a bit intimidating for my limited experience level with OCaml. 😬

What do you find intimidating ?

**Comment by vphantom** [comment]
> UTF-8 doesn't care about grapheme clusters. So I'm not sure what keeping grapheme clusters intact has to do with being "UTF-8 friendly".

On the contrary, _using_ UTF-8 certainly makes grapheme clusters matter.  For example "🇨🇦" is two "code points".  I'm not too sure about "graphemes" vs "grapheme clusters" but according to <https://unicode.org/reports/tr29/> a "grapheme cluster" is a single perceived character for the end user.  Therefore, I consider them to be indivisible, like this flag as a 4-byte atom.


> But then I find your specification of `truncate` a bit curious. I'm not sure I see a use for defining a length in terms of bytes and then truncate according to grapheme clusters. When dealing with text you want to truncate e.g. for display, so indicating `max_len` in bytes seems unhelpful.

I deal with strings/bytes everywhere, for example in binary serializer applications (Protobuf, CBOR, etc.)  Using slices is common in parser and I/O applications where reducing unnecessary memory copying yields a significant performance improvement at little cost.  So a lot of my processing functions take `?pos:int -> ?len:int -> bytes` as input instead of just `bytes` (or `string`) to optionally restrict their reading to a slice of a larger area.  Suppose that I'm decoding a 1MB Protobuf message which contains a 300-byte UTF-8 string, which I then want to process in a few ways including truncation to 255 bytes for storage in a limited DB column.  My parser returns an `int * int * string` slice which I read directly without allocating a copy.  It's a bit like how `Bigarray.Array1.sub` doesn't copy data to make a smaller "window", but here it's managed manually.


> doing it yourself with the streaming segmenters for now (just look at the code).

Ah yes, I think I see what you mean. I would have to duplicate your private `fold` from <https://github.com/dbuenzli/uuseg/blob/master/src/uuseg_string.ml#L8> in order to make use of `Uutf.String.fold_utf_8`'s `?pos` and `?len` parameters.  I might even be able to count bytes instead of storing them in a temporary `Buffer.t`…  I'll look into that, thanks.


> What do you find intimidating ?

It's not a complaint, just a general observation.  You're clearly a very advanced developer.  You use the type system and the functional properties of OCaml thoroughly to achieve your goals and it makes my initial approach to a given module very daunting.  (I needed a solid hour to grasp the basics of `Cmdliner`…)

**Comment by dbuenzli** [comment]
> On the contrary, _using_ UTF-8 certainly makes grapheme clusters matter.

It's not UTF-8 that makes grapheme clusters matter. It's using Unicode text. UTF-8 just cares about encoding sequences of Unicode scalar values. 

You may take that point of view as pedantic, but I insist on this because a lot of the confusion that arises in programmers head is because they constantly conflate Unicode text with its encodings (i.e. byte serializations).

> Suppose that I'm decoding a 1MB Protobuf message which contains a 300-byte UTF-8 string, which I then want to process in a few ways including truncation to 255 bytes for storage in a limited DB column.

Well truncating on a grapheme cluster or a Unicode scalar value is going to be the same for end-user: data loss and extremely annoying, if not a security risk. 

First you should design your system up front so that user data does not get unknowingly truncated (e.g. limited input fields). Second failing to this, you should consider erroring loudly in this case. Third if you really have to truncate a much more sensitive system would be to 1) always retain as much as possible of the user data and 2) indicate that something was lost by ending the sequence with U+FFFD. Note that none of this requires working at the grapheme cluster level, only at the encoding, i.e. UTF-8 level.

By trying to be smart you make it harder to understand that a truncation occurred and where exactly it occurred.

> You use the type system and the functional properties of OCaml thoroughly to achieve your goals and it makes my initial approach to a given module very daunting.

I don't exactly see what is daunting in `Uuseg_string`. I find this comment rather suprising my APIs are rather bland type wise and very conservative in using type system tricks (because encoding problems at the type level tends not to be very usable in practice). 

Regarding being intimidated by my use of the functional properties of OCaml that is rather surprising, functional code is much easier to grasp than mutable code.

**Comment by vphantom** [comment]
> You may take that point of view as pedantic, but I insist on this because a lot of the confusion that arises in programmers head is because they constantly conflate Unicode text with its encodings (i.e. byte serializations).

Definitions aside, my point is to have a functional product and that means that if I'm required to truncate a string and not crash, or to process a stream of "characters", I want those to be user-perceived and not bytes or even code points.  Just like a hypothetical `summary : max_len:int -> string -> string` function might consider whole words.

> First you should design your system up front so that user data does not get unknowingly truncated (e.g. limited input fields).

I was making a simple, fictitious example.  It is of course a very good idea to refuse data loss.  In practice my first use case was an EDI conversion between accounting systems which requires truncation to specific byte lengths.  Our users expect silent truncation if the data source was too verbose, which is common and harmless for product names and descriptions for example.  In that context I want don't want to break the last grapheme cluster if it would not fit.  (Our initial trading partner just uses uppercase 7-bit ASCII, _really_ old-school, but the format has an UTF-8 mode hence my desire to behave well with it.)

> Regarding being intimidated by my use of the functional properties of OCaml that is rather surprising, functional code is much easier to grasp than mutable code.

I'm fine with FP; I use it every day myself and I mostly enjoy OCaml's expressiveness (it's why I chose it for our full rewrite).  It's tough to explain clearly…  I think it has more to do with how each of us visualizes control flow.  I typically understand source code in the Stdlib or Containers quicker than yours; you're probably just comfortable with more levels of abstraction than what I'm used to.  Admittedly I'd do much better if I had the benefit of Merlin when I browse sources on GitHub; there would be fewer "what the heck are they doing there?" moments. 😉
